[2025-03-03T16:38:17.852+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dvc_pipeline_V2.Check_reference_file manual__2025-03-03T16:38:00.659930+00:00 [queued]>
[2025-03-03T16:38:17.877+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dvc_pipeline_V2.Check_reference_file manual__2025-03-03T16:38:00.659930+00:00 [queued]>
[2025-03-03T16:38:17.878+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T16:38:17.905+0000] {taskinstance.py:2191} INFO - Executing <Task(BranchPythonOperator): Check_reference_file> on 2025-03-03 16:38:00.659930+00:00
[2025-03-03T16:38:17.919+0000] {standard_task_runner.py:60} INFO - Started process 142 to run task
[2025-03-03T16:38:17.931+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dvc_pipeline_V2', 'Check_reference_file', 'manual__2025-03-03T16:38:00.659930+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/new_dag.py', '--cfg-path', '/tmp/tmpro8bruz4']
[2025-03-03T16:38:17.936+0000] {standard_task_runner.py:88} INFO - Job 132: Subtask Check_reference_file
[2025-03-03T16:38:17.977+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-03T16:38:18.090+0000] {task_command.py:423} INFO - Running <TaskInstance: dvc_pipeline_V2.Check_reference_file manual__2025-03-03T16:38:00.659930+00:00 [running]> on host d9436bd0e43c
[2025-03-03T16:38:18.477+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dvc_pipeline_V2' AIRFLOW_CTX_TASK_ID='Check_reference_file' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T16:38:00.659930+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T16:38:00.659930+00:00'
[2025-03-03T16:38:18.487+0000] {python.py:201} INFO - Done. Returned value was: data_drift_monitoring
[2025-03-03T16:38:18.488+0000] {branch.py:35} INFO - Branch into data_drift_monitoring
[2025-03-03T16:38:18.508+0000] {skipmixin.py:178} INFO - Following branch data_drift_monitoring
[2025-03-03T16:38:18.546+0000] {skipmixin.py:244} INFO - Skipping tasks []
[2025-03-03T16:38:18.605+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dvc_pipeline_V2, task_id=Check_reference_file, execution_date=20250303T163800, start_date=20250303T163817, end_date=20250303T163818
[2025-03-03T16:38:18.668+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-03T16:38:18.742+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
