[2025-03-03T15:25:54.864+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dvc_pipeline_V2.Check_reference_file manual__2025-03-03T15:25:28.748757+00:00 [queued]>
[2025-03-03T15:25:54.880+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dvc_pipeline_V2.Check_reference_file manual__2025-03-03T15:25:28.748757+00:00 [queued]>
[2025-03-03T15:25:54.881+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T15:25:54.905+0000] {taskinstance.py:2191} INFO - Executing <Task(BranchPythonOperator): Check_reference_file> on 2025-03-03 15:25:28.748757+00:00
[2025-03-03T15:25:54.922+0000] {standard_task_runner.py:60} INFO - Started process 143 to run task
[2025-03-03T15:25:54.928+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dvc_pipeline_V2', 'Check_reference_file', 'manual__2025-03-03T15:25:28.748757+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/new_dag.py', '--cfg-path', '/tmp/tmpgt1wy40i']
[2025-03-03T15:25:54.933+0000] {standard_task_runner.py:88} INFO - Job 105: Subtask Check_reference_file
[2025-03-03T15:25:54.956+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-03T15:25:55.075+0000] {task_command.py:423} INFO - Running <TaskInstance: dvc_pipeline_V2.Check_reference_file manual__2025-03-03T15:25:28.748757+00:00 [running]> on host 99d7c207cb9e
[2025-03-03T15:25:55.411+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dvc_pipeline_V2' AIRFLOW_CTX_TASK_ID='Check_reference_file' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T15:25:28.748757+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T15:25:28.748757+00:00'
[2025-03-03T15:25:55.416+0000] {python.py:201} INFO - Done. Returned value was: data_drift_monitoring
[2025-03-03T15:25:55.417+0000] {branch.py:35} INFO - Branch into data_drift_monitoring
[2025-03-03T15:25:55.423+0000] {skipmixin.py:178} INFO - Following branch data_drift_monitoring
[2025-03-03T15:25:55.479+0000] {skipmixin.py:244} INFO - Skipping tasks []
[2025-03-03T15:25:55.538+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dvc_pipeline_V2, task_id=Check_reference_file, execution_date=20250303T152528, start_date=20250303T152554, end_date=20250303T152555
[2025-03-03T15:25:55.583+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-03T15:25:55.629+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
