[2025-02-25T01:49:19.943+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dvc_pipeline.data_drift_detection manual__2025-02-25T01:46:10.943774+00:00 [queued]>
[2025-02-25T01:49:19.959+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dvc_pipeline.data_drift_detection manual__2025-02-25T01:46:10.943774+00:00 [queued]>
[2025-02-25T01:49:19.960+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-02-25T01:49:19.986+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): data_drift_detection> on 2025-02-25 01:46:10.943774+00:00
[2025-02-25T01:49:19.997+0000] {standard_task_runner.py:60} INFO - Started process 542 to run task
[2025-02-25T01:49:20.004+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dvc_pipeline', 'data_drift_detection', 'manual__2025-02-25T01:46:10.943774+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline_dag.py', '--cfg-path', '/tmp/tmprvyq4a8n']
[2025-02-25T01:49:20.008+0000] {standard_task_runner.py:88} INFO - Job 89: Subtask data_drift_detection
[2025-02-25T01:49:20.030+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-02-25T01:49:20.095+0000] {task_command.py:423} INFO - Running <TaskInstance: dvc_pipeline.data_drift_detection manual__2025-02-25T01:46:10.943774+00:00 [running]> on host 7efe327aec71
[2025-02-25T01:49:20.248+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dvc_pipeline' AIRFLOW_CTX_TASK_ID='data_drift_detection' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T01:46:10.943774+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-25T01:46:10.943774+00:00'
[2025-02-25T01:49:42.619+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-02-25T01:49:42.643+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dvc_pipeline, task_id=data_drift_detection, execution_date=20250225T014610, start_date=20250225T014919, end_date=20250225T014942
[2025-02-25T01:49:42.691+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-02-25T01:49:42.714+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
