[2025-03-03T16:38:20.860+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dvc_pipeline_V2.data_drift_monitoring manual__2025-03-03T16:38:00.659930+00:00 [queued]>
[2025-03-03T16:38:20.880+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dvc_pipeline_V2.data_drift_monitoring manual__2025-03-03T16:38:00.659930+00:00 [queued]>
[2025-03-03T16:38:20.882+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T16:38:20.903+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): data_drift_monitoring> on 2025-03-03 16:38:00.659930+00:00
[2025-03-03T16:38:20.912+0000] {standard_task_runner.py:60} INFO - Started process 145 to run task
[2025-03-03T16:38:20.917+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dvc_pipeline_V2', 'data_drift_monitoring', 'manual__2025-03-03T16:38:00.659930+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/new_dag.py', '--cfg-path', '/tmp/tmp52kup4vz']
[2025-03-03T16:38:20.920+0000] {standard_task_runner.py:88} INFO - Job 133: Subtask data_drift_monitoring
[2025-03-03T16:38:20.951+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-03T16:38:21.003+0000] {task_command.py:423} INFO - Running <TaskInstance: dvc_pipeline_V2.data_drift_monitoring manual__2025-03-03T16:38:00.659930+00:00 [running]> on host d9436bd0e43c
[2025-03-03T16:38:21.105+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dvc_pipeline_V2' AIRFLOW_CTX_TASK_ID='data_drift_monitoring' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T16:38:00.659930+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T16:38:00.659930+00:00'
[2025-03-03T16:38:21.108+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-03T16:38:21.111+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/src/data/drift_monitoring.py']
[2025-03-03T16:38:21.126+0000] {subprocess.py:86} INFO - Output:
[2025-03-03T16:38:30.449+0000] {subprocess.py:93} INFO - 2025-03-03 16:38:30,449 - INFO - Loading datasets for drift detection
[2025-03-03T16:38:33.817+0000] {subprocess.py:93} INFO - 2025-03-03 16:38:33,815 - INFO - Running Evidently drift detection
[2025-03-03T16:38:47.627+0000] {subprocess.py:93} INFO - 2025-03-03 16:38:47,627 - INFO - Drift result saved to: /opt/***/metrics/data_drift.json
[2025-03-03T16:38:51.297+0000] {subprocess.py:93} INFO - 2025-03-03 16:38:51,296 - INFO - Drift report saved to: /opt/***/reports/data_drift.html
[2025-03-03T16:38:51.299+0000] {subprocess.py:93} INFO - 2025-03-03 16:38:51,297 - INFO - Drift score: 0.5
[2025-03-03T16:38:51.302+0000] {subprocess.py:93} INFO - 2025-03-03 16:38:51,297 - INFO - No significant drift. Model remains unchanged.
[2025-03-03T16:38:51.302+0000] {subprocess.py:93} INFO - 2025-03-03 16:38:51,297 - INFO - No retraining needed.
[2025-03-03T16:38:52.178+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-03T16:38:52.234+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dvc_pipeline_V2, task_id=data_drift_monitoring, execution_date=20250303T163800, start_date=20250303T163820, end_date=20250303T163852
[2025-03-03T16:38:52.299+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-03T16:38:52.350+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
