[2025-03-03T15:47:18.092+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dvc_pipeline_V2.Check_reference_file manual__2025-03-03T15:47:08.955155+00:00 [queued]>
[2025-03-03T15:47:18.102+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dvc_pipeline_V2.Check_reference_file manual__2025-03-03T15:47:08.955155+00:00 [queued]>
[2025-03-03T15:47:18.103+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-03-03T15:47:18.119+0000] {taskinstance.py:2191} INFO - Executing <Task(BranchPythonOperator): Check_reference_file> on 2025-03-03 15:47:08.955155+00:00
[2025-03-03T15:47:18.128+0000] {standard_task_runner.py:60} INFO - Started process 154 to run task
[2025-03-03T15:47:18.133+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dvc_pipeline_V2', 'Check_reference_file', 'manual__2025-03-03T15:47:08.955155+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/new_dag.py', '--cfg-path', '/tmp/tmpk76ilqd4']
[2025-03-03T15:47:18.136+0000] {standard_task_runner.py:88} INFO - Job 108: Subtask Check_reference_file
[2025-03-03T15:47:18.154+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-03T15:47:18.199+0000] {task_command.py:423} INFO - Running <TaskInstance: dvc_pipeline_V2.Check_reference_file manual__2025-03-03T15:47:08.955155+00:00 [running]> on host 99d7c207cb9e
[2025-03-03T15:47:18.329+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dvc_pipeline_V2' AIRFLOW_CTX_TASK_ID='Check_reference_file' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T15:47:08.955155+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T15:47:08.955155+00:00'
[2025-03-03T15:47:18.334+0000] {python.py:201} INFO - Done. Returned value was: data_drift_monitoring
[2025-03-03T15:47:18.335+0000] {branch.py:35} INFO - Branch into data_drift_monitoring
[2025-03-03T15:47:18.336+0000] {skipmixin.py:178} INFO - Following branch data_drift_monitoring
[2025-03-03T15:47:18.404+0000] {skipmixin.py:244} INFO - Skipping tasks []
[2025-03-03T15:47:18.549+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dvc_pipeline_V2, task_id=Check_reference_file, execution_date=20250303T154708, start_date=20250303T154718, end_date=20250303T154718
[2025-03-03T15:47:18.653+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-03-03T15:47:18.783+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
